---
- hosts: localhost
  name: Installing dependencies using npm
  tasks:
    - name: Installing chokidar
      npm:
        name: chokidar
        path: ./
        state: latest
    - name: Installing pouchdb
      npm:
        name: pouchdb
        path: ./
        state: latest
    - name: Installing pouchdb-server
      npm:
        name: pouchdb-server
        global: True
    - name: Installing uuid
      npm:
        name: uuid
        path: ./
        state: latest
    - name: Install Scout server service
      command: cp ./services/scout_server.service /etc/systemd/system/scout_server.service
    - name: Create Scout directory
      file:
        path: /opt/scout
        state: directory
    - name: Create database directory
      file:
        path: /opt/scout/database
        state: directory